apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprofile
        image: vprocontainers/vprofiledb
        ports:
        - containerPort: 3306
          name: dbport
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-storage
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - "-h"
            - "localhost"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - sh
              - "-c"
              - "mysql -uroot -p$MYSQL_PASSWORD -e 'SELECT 1'"
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql